baseurl: http://replace-this-with-your-hugo-site.com/
languageCode: en-us
title: Aerobatic
PygmentsCodeFences: true
pygmentsuseclasses: true
pygmentsstripall: true

permalinks:
  blog: /blog/:slug/

params:
  prompt: "[cwd]:$"
  registerUrl: https://control.aerobatic.com/register
  social:
    - title: twitter
      url: http://twitter.com/aerobaticapp
    - title: bitbucket
      url: http://bitbucket.org/aerobatic
    - title: github-alt
      url: http://github.com/aerobatic
