version: 2
jobs:
  build-deploy-job:
    docker:
      - image: circleci/node:8.11

    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: wget https://github.com/gohugoio/hugo/releases/download/v0.32.4/hugo_0.32.4_Linux-64bit.deb
      - run: sudo dpkg -i hugo*.deb
      - run: npm install
      - run: npm install aerobatic-cli
      - run: NODE_ENV=production npm run build:aerobatic

      - run:
          name: Deploy based on branch
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]
            then
              echo 'Deploy to production'
              ./node_modules/.bin/aero deploy
            else
              echo 'No deploy for branch $CIRCLE_BRANCH'
            fi

      # Save dependency cache
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-job
